apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: tempo
  labels:
    app: tempo
spec:
  replicas: 1
  serviceName: tempo
  selector:
    matchLabels:
      app: tempo
  template:
    metadata:
      labels:
        app: tempo
    spec:
      securityContext:
        fsGroup: 10001
        runAsUser: 10001
      containers:
        - name: tempo
          image: grafana/tempo:2.8.2
          args:
            - "-config.file=/etc/tempo/tempo.yaml"
          ports:
            - name: http
              containerPort: 3200
            - name: grpc
              containerPort: 4317
            - name: otlp-http
              containerPort: 4318
          volumeMounts:
            - mountPath: /etc/tempo
              name: tempo-config
              readOnly: true
            - mountPath: /tmp/tempo/wal
              name: tempo-wal
          resources:
            limits:
              memory: 2Gi
              cpu: "1"
            requests:
              memory: 1Gi
              cpu: "500m"
          envFrom:
            - secretRef:
                name: tempo-s3
      volumes:
        - name: tempo-config
          configMap:
            name: tempo-config
      nodeSelector:
        size: medium
  volumeClaimTemplates:
    - metadata:
        name: tempo-wal
      spec:
        accessModes: [ "ReadWriteOnce" ]
        storageClassName: "nvme.network-drives.csi.timeweb.cloud"
        resources:
          requests:
            storage: 10Gi