apiVersion: v1
kind: Secret
metadata:
  name: user-secret
type: Opaque
stringData:
  REDISSON_USERNAME: ""
  REDISSON_PASSWORD: "jsdfnsdfnsdfnkjsadf3"

  SPRING_DATASOURCE_USERNAME: ""
  SPRING_DATASOURCE_PASSWORD: "jsdfnsdfnsdfnkjsadf3"

  SPRING_KAFKA_PROPERTIES_SASL_JAAS_CONFIG: "org.apache.kafka.common.security.scram.ScramLoginModule required username='gen_user' password='jsdfnsdfnsdfnkjsadf3';"

  SPRING_FLYWAY_USER: ""
  SPRING_FLYWAY_PASSWORD: "jsdfnsdfnsdfnkjsadf3"