apiVersion: apps/v1
kind: Deployment
metadata:
  name: catalog-deployment
  labels:
    app: catalog-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: catalog-service
  template:
    metadata:
      name: catalog-service
      labels:
        app: catalog-service
    spec:
      containers:
        - name: catalog-service
          image: stroy1click/catalog:0.0.1-SNAPSHOT
          imagePullPolicy: Always
          ports:
            - containerPort: 7070
              protocol: TCP
          envFrom:
            - configMapRef:
                name: catalog-service-config
            - secretRef:
                name: catalog-secret
          livenessProbe:
            httpGet:
              port: 7070
              path: /actuator/health
            initialDelaySeconds: 60
            periodSeconds: 5
            failureThreshold: 3
          readinessProbe:
            httpGet:
              port: 7070
              path: /actuator/health
            initialDelaySeconds: 240
            periodSeconds: 5
            failureThreshold: 3
          resources:
            requests:
              memory: "512Mi"
              cpu: "250m"
            limits:
              memory: "1Gi"
              cpu: "500m"
      restartPolicy: Always
      nodeSelector:
        size: large
