apiVersion: v1
kind: Secret
metadata:
  name: catalog-secret
type: Opaque
stringData:
  REDISSON_USERNAME: ""
  REDISSON_PASSWORD: ""

  SPRING_DATASOURCE_USERNAME: ""
  SPRING_DATASOURCE_PASSWORD: ""

  SPRING_FLYWAY_USER: ""
  SPRING_FLYWAY_PASSWORD: ""