apiVersion: v1
kind: Secret
metadata:
  name: email-secret
type: Opaque
stringData:
  SPRING_KAFKA_PROPERTIES_SASL_JAAS_CONFIG: "org.apache.kafka.common.security.scram.ScramLoginModule required username='gen_user' password='jsdfnsdfnsdfnkjsadf3';"