apiVersion: apps/v1
kind: Deployment
metadata:
  name: document-deployment
  labels:
    app: document-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: document-service
  template:
    metadata:
      name: document-service
      labels:
        app: document-service
    spec:
      containers:
        - name: document-service
          image: stroy1click/document:0.0.1-SNAPSHOT
          imagePullPolicy: Always
          ports:
            - containerPort: 6065
              protocol: TCP
          envFrom:
            - configMapRef:
                name: document-service-config
            - secretRef:
                name: document-secret
          livenessProbe:
            httpGet:
              port: 6065
              path: /actuator/health
            initialDelaySeconds: 60
            periodSeconds: 5
            failureThreshold: 3
          readinessProbe:
            httpGet:
              port: 6065
              path: /actuator/health
            initialDelaySeconds: 240
            periodSeconds: 5
            failureThreshold: 3
          resources:
            requests:
              memory: "512Mi"
              cpu: "250m"
            limits:
              memory: "1Gi"
              cpu: "500m"
      restartPolicy: Always
      nodeSelector:
        size: large