apiVersion: v1
kind: Secret
metadata:
  name: document-secret
type: Opaque
stringData:
  REDISSON_USERNAME: ""
  REDISSON_PASSWORD: ""

  SPRING_DATASOURCE_USERNAME: ""
  SPRING_DATASOURCE_PASSWORD: ""

  SPRING_KAFKA_PROPERTIES_SASL_JAAS_CONFIG: "org.apache.kafka.common.security.scram.ScramLoginModule required username='document-service' password='dfjsfd324u2y5u34';"

  SPRING_FLYWAY_USER: ""
  SPRING_FLYWAY_PASSWORD: ""