apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: prod

resources:
  - attribute
  - auth
  - confirmationcode
  - email
  - notification
  - order
  - catalog
  - user
  - jwtvalidator