apiVersion: apps/v1
kind: Deployment
metadata:
  name: catalog-deployment
  labels:
    app: catalog-service
  namespace: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: catalog-service
  template:
    metadata:
      name: catalog-service
      labels:
        app: catalog-service
    spec:
      containers:
        - name: catalog-service
          image: stroy1click/catalog:0.0.1-SNAPSHOT
          imagePullPolicy: Always
          ports:
            - containerPort: 7070
              protocol: TCP
          envFrom:
            - configMapRef:
                name: catalog-service-config
          livenessProbe:
            httpGet:
              port: 4040
              path: /actuator/health
            initialDelaySeconds: 20
            periodSeconds: 5
            failureThreshold: 3

      restartPolicy: Always
