apiVersion: v1
kind: ConfigMap
metadata:
  name: auth-service-config
data:
  SPRING_PROFILES_ACTIVE: "prod"

  SPRING_DATASOURCE_URL: "jdbc:postgresql://auth-db:5437/stroy1click"
  SPRING_DATASOURCE_DRIVER_CLASS_NAME: "org.postgresql.Driver"
  SPRING_FLYWAY_URL: "jdbc:postgresql://auth-db:5437/stroy1click"
  SPRING_FLYWAY_BASELINE_ON_MIGRATE: "true"

  SPRING_KAFKA_BOOTSTRAP_SERVERS: "kafka:9092"
  SPRING_KAFKA_PRODUCER_KEY_SERIALIZER: "org.apache.kafka.common.serialization.StringSerializer"
  SPRING_KAFKA_PRODUCER_VALUE_SERIALIZER: "org.springframework.kafka.support.serializer.JsonSerializer"
  SPRING_KAFKA_CONSUMER_KEY_DESERIALIZER: "org.apache.kafka.common.serialization.StringDeserializer"
  SPRING_KAFKA_CONSUMER_VALUE_DESERIALIZER: "org.springframework.kafka.support.serializer.JsonDeserializer"
  SPRING_KAFKA_CONSUMER_GROUP_ID: "auth-service"
  SPRING_KAFKA_CONSUMER_PROPERTIES_SPRING_JSON_TRUSTED_PACKAGES: "ru.stroy1click.common.*"
  SPRING_KAFKA_PROPERTIES_SECURITY_PROTOCOL: "SASL_PLAINTEXT"
  SPRING_KAFKA_PROPERTIES_SASL_MECHANISM: "SCRAM-SHA-512"

  URL_USER: "http://user-service:8080/api/v1/users"

  SERVER_ADDRESS: "0.0.0.0"

  OTEL_SERVICE_NAME: "auth-service"
  OTEL_TRACES_EXPORTER: "otlp"
  OTEL_TRACES_SAMPLER: "always_on"
  OTEL_METRICS_EXPORTER: "otlp"
  OTEL_METRICS_EXPORT_INTERVAL: "5000"
  OTEL_LOGS_EXPORTER: "otlp"
  OTEL_EXPORTER_OTLP_PROTOCOL: "grpc"
  OTEL_EXPORTER_OTLP_ENDPOINT: "http://otel-collector:4317"