apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: stroy1click-ingress
  annotations:
    nginx.ingress.kubernetes.io/auth-url: "http://jwt-validator-service.prod.svc.cluster.local:9050/api/v1/jwt/validate"
    nginx.ingress.kubernetes.io/auth-request-redirect: "$request_uri"

    nginx.ingress.kubernetes.io/proxy-body-size: "50m"

    nginx.ingress.kubernetes.io/auth-proxy-set-headers: "prod/auth-proxy-headers"

    nginx.ingress.kubernetes.io/cors-allow-origin: "https://novacodeltd.ru"
    nginx.ingress.kubernetes.io/cors-allow-methods: "GET, POST, PATCH, DELETE, OPTIONS"
    nginx.ingress.kubernetes.io/cors-allow-headers: "Authorization, Content-Type"
    nginx.ingress.kubernetes.io/cors-allow-credentials: "true"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - api.stroy1click.ru
      secretName: stroy1click-tls
  rules:
    - host: api.stroy1click.ru
      http:
        paths:
          - path: /api/v1/products
            pathType: Prefix
            backend:
              service:
                name: product-service
                port:
                  number: 7070
    - host: api.stroy1click.ru
      http:
        paths:
          - path: /api/v1/categories
            pathType: Prefix
            backend:
              service:
                name: product-service
                port:
                  number: 7070
    - host: api.stroy1click.ru
      http:
        paths:
          - path: /api/v1/subcategories
            pathType: Prefix
            backend:
              service:
                name: product-service
                port:
                  number: 7070
    - host: api.stroy1click.ru
      http:
        paths:
          - path: /api/v1/product-types
            pathType: Prefix
            backend:
              service:
                name: product-service
                port:
                  number: 7070
    - host: api.stroy1click.ru
      http:
        paths:
          - path: /api/v1/storage
            pathType: Prefix
            backend:
              service:
                name: product-service
                port:
                  number: 7070
    - host: api.stroy1click.ru
      http:
        paths:
          - path: /api/v1/orders
            pathType: Prefix
            backend:
              service:
                name: order-service
                port:
                  number: 1010
    - host: api.stroy1click.ru
      http:
        paths:
          - path: /api/v1/users
            pathType: Prefix
            backend:
              service:
                name: user-service
                port:
                  number: 8080
    - host: api.stroy1click.ru
      http:
        paths:
          - path: /api/v1/attributes
            pathType: Prefix
            backend:
              service:
                name: attribute-service
                port:
                  number: 4040
    - host: api.stroy1click.ru
      http:
        paths:
          - path: /api/v1/attribute-options
            pathType: Prefix
            backend:
              service:
                name: attribute-service
                port:
                  number: 4040
    - host: api.stroy1click.ru
      http:
        paths:
          - path: /api/v1/product-attribute-assignments
            pathType: Prefix
            backend:
              service:
                name: attribute-service
                port:
                  number: 4040
    - host: api.stroy1click.ru
      http:
        paths:
          - path: /api/v1/notification
            pathType: Prefix
            backend:
              service:
                name: notification-service
                port:
                  number: 2020
    - host: api.stroy1click.ru
      http:
        paths:
          - path: /api/v1/confirmation-codes
            pathType: Prefix
            backend:
              service:
                name: confirmation-code-service
                port:
                  number: 6060
    - host: api.stroy1click.ru
      http:
        paths:
          - path: /api/v1/emails
            pathType: Prefix
            backend:
              service:
                name: email-service
                port:
                  number: 5050
    - host: api.stroy1click.ru
      http:
        paths:
          - path: /api/v1/auth
            pathType: Prefix
            backend:
              service:
                name: auth-service
                port:
                  number: 9070
