apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: prod

resources:
  - api-ingress.yaml
  - configmap.yaml
  - endpoint.yaml
  - api-ingress-secret.yaml
  - namespace.yaml
  - redis.yaml